version: "2"

services:
  sonosserver:
    build: .
    # with the following line, an alternativ python app could be started
    # command: python3 sonosServer.py 
    ports:
      - "5000:5000"
    volumes:
      - ./code:/code
    restart: always
    network_mode: "host"

